# plotting_for_foci_quantification_single.R, Radoslaw Grochowski, Karolinska Institutet
# 28.02.20

# This script generates single plots for foci quantification: population 
# histograms and violin plots with boxplots from data generated by CellProfiler's 
# (Version 3.1.8) pipelines like 'CellProfiler_nuclear_foci_quantification.cppipe'.
# The input .csv file contains single cell data on the per-nuclei foci count and
# size and intensity of each foci. This script visualizes only the first type of
# data.

# Output .png files will be saved in the automatically generated output
# sub-folder of the working directory.


### Procede with the code by localizing the caret on the line of code to execute and by 
### pressing CRTL + ENTER, changing some of the variables to fit Your dataset and to format plots.


install.packages(c('ggplot2', 'data.table', 'ggpubr'))
library(ggplot2)
library(ggpubr)
library(data.table)



# Set the input directory with the nuclei.csv file.
dir_1 <- '~/experiment/data'
dir.create(dir_1)
setwd(dir_1)

# Load the segmentation output file and change the Metadata_FOLDER column class to factor.
nuc <- fread('nuclei.csv')
nuc[, Metadata_FOLDER := as.factor(Metadata_FOLDER)]

# Set the output directiory for the plots.
dir_2 <- 'foci_quantification_-_boxplots_and_histograms_single'
dir.create(paste0(dir_1, '/', dir_2))
setwd(paste0(dir_1, '/', dir_2))


# Set the name of the column with foci counts as a variable which will be used for plotting.
foci_count <- 'Children_Foci_......_Count'

# Show the order of Metadata_FOLDER labels.
nuc[, levels(Metadata_FOLDER)]

# Make a vector containing those labels
ID <- c(nuc[, levels(Metadata_FOLDER)])

# List conditions/treatments used in the same order as the corresponding Metadata_FOLDER labels.
label <- c('treatment 1, cell type 1', 'treatment 2, cell type 2', 'treatment 2, cell type 1', 'treatment 2, cell type 2')

# Make a data.table with labels.
cond <- data.table(Metadata_FOLDER = as.factor(ID), label)

# Add columns with labels to the dataset and set their class to factor.
nuc_cat <- nuc[cond, on = 'Metadata_FOLDER']
nuc_cat[, label := as.factor(label)]


# Statistics to be shown on plots.
stat <- nuc_cat[, .(mean = mean(get(foci_count)),
          median = as.double(median(get(foci_count))), 
          sd = sd(get(foci_count)),
          n = sum(get(foci_count))), by = label]

# Save the statistics as a table.
write.table(stat, file = 'foci_quantification_table.txt', quote = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)



#### PLOTTING

# Change the default theme used by ggplot2.
theme_new <- theme_set(theme_gray())
theme_new <- theme_update(
 axis.text.x=element_text(vjust = 0.5),
 strip.background = element_rect(fill='#FFFFFF'),
 plot_title = element_text(hjust = 0.5),
 axis.title=element_text(size=13),
 axis.text=element_text(size=11)
)


# Order the labels as in the initial vectors.
nuc_cat$label = factor(nuc_cat$label, levels = unique(cond$label))
stat$label = factor(stat$label, levels = unique(cond$label))

# Set limits for the x axis - first number is the lower limit, second - upper.
h <- c(-5, 35)

# Position vertically the labels with the statistical summaries.
lab_pos <- 10

# Set the width and height in inches for the output png file.
plot_width <- 5
plot_height <- 4

# Set the title of the plot.
plot_title <- 'Title of this plot'

# Plot data for each label.
for (i in label) {
 
 boxplot <- ggplot(nuc_cat[label == i], aes(x = label, y = get(foci_count))) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, width = .25) +
  geom_errorbar(data = stat[label == i], aes(x = label, ymin = mean - sd, ymax = mean + sd), width=.1, inherit.aes = F) +
  geom_text(data = stat, aes(label = paste('mean =', round(mean,digits=2), '\n', 
                       'median =', round(median, digits=2), '\n',
                       'cell count =', n_cells, '\n', 
                       'foci count =', n_foci), y = lab_pos), 
       nudge_x = .3, size = 3, check_overlap = TRUE) +
  ylab('Foci Count') +
  xlab('') +
  coord_cartesian(ylim = h) +
  guides(colour = F, size = F) +
  ggtitle(plot_title)
 
 
 # Save the plot as a png file.
 ggsave(plot = boxplot,
     paste0('output_boxplot_', plot_title, '_', i, '.png'),  
     scale = 1.3, dpi = 600,
     width = plot_width, height = plot_height,
     units = 'in')

}




# --------------------------------------



### Plot the histogram.

# Set limits for the x axis.
lim_hist <- c(0, 30) 

# Position the labels - first number is x, second is y.
lab_pos <- c(10, 20)

# Choose the bin size.
bin_size <- 30


for (i in label) {
 
 histogram <- ggplot(nuc_cat[label == i]) +
  geom_histogram(aes(x = get(foci_count),
            y = 100*..count.. / sapply(PANEL, FUN=function(x) sum(count[PANEL == x])), 
            
            alpha=I(.8)), bins = bin_size) +
  facet_wrap(~label) +
  geom_vline(data = stat[label == i],
        aes(xintercept = mean),
        color = '#E69F00', size=1) +
  geom_vline(data = stat[label == i],
        aes(xintercept = median),
        color = '#56B4E9', size=1) +
  geom_text(data = stat[label == i], aes(label = paste('mean =', round(mean,digits=2)), x = lab_pos[1], y = lab_pos[2]), 
       nudge_x = .3, nudge_y = 8, color = '#E69F00',
       size = 3, check_overlap = T) +
  geom_text(data = stat[label == i], aes(label = paste('median =', round(median, digits=2)), x = lab_pos[1], y = lab_pos[2]), 
       nudge_x = .3, nudge_y = 5, color = '#56B4E9',
       size = 3, check_overlap = TRUE) +
  geom_text(data = stat[label == i], aes(label = paste('n =', n), x = lab_pos[1], y = lab_pos[2]), 
       nudge_x = .3, nudge_y = 2,
       size = 3, check_overlap = TRUE) +
  coord_cartesian(xlim = c(lim_hist[1], lim_hist[2])) +
  ylab('Relative frequency [%]') +
  xlab('') +
  ggtitle(plot_title) 
 
 
 # Save the plot as a png file.
  ggsave(plot = histogram,
     paste0('output_histogram_', plot_title, '_', i, '.png'),  
     scale = 1.3, dpi = 600,
     width = plot_width, height = plot_height,
     units = 'in')
 
 
 
}



 
#### DOCUMENT THE ANALYSIS SESSION AND SAVE THE WORKSPACE
writeLines(capture.output(sessionInfo()), 'sessionInfo.txt')
save.image(file = 'workspace.RData')
